## definimos el tipo de base de datos
quarkus.datasource.db-kind=postgresql
## Usuario con el que se conecta a la base de datos
quarkus.datasource.username=postgres
## contraseña del usuario
quarkus.datasource.password=labcom,2015
## URL de conexion a la base de datos
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pa2DB

##parametros recomendables
quarkus.hibernate-orm.database.generation=drop-and-create
##quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.log.sql=true
##timeout de la transaccion por defecto
quarkus.transaction-manager.default-transaction-timeout=PT240S